#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DroidTest.Resource", IsApplication=true)]

namespace DroidTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_up = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int planets_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bottomline = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonSignUpStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int drawer_shadow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_text_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_add_box_black_48dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_add_box_white_48dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_add_circle_black_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_add_circle_black_48dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_add_circle_outline_black_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_add_circle_outline_white_48dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_add_circle_white_24dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_cached_black_48dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_cached_white_48dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_camera_alt_black_48dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_camera_alt_white_48dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_check_circle_white_48dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_drawer = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_filter_list_black_48dp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_highlight_off_white_48dp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_launcher = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_more_vert_black_48dp = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_remove_circle_outline_white_48dp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Icon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int monoandroidsplash = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int progress_info = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int topline = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090018
			public const int Text = 2131296280;
			
			// aapt resource value: 0x7f090061
			public const int add_attendance = 2131296353;
			
			// aapt resource value: 0x7f090062
			public const int add_photo = 2131296354;
			
			// aapt resource value: 0x7f090052
			public const int btnDialogEmail = 2131296338;
			
			// aapt resource value: 0x7f09005e
			public const int checkBox1 = 2131296350;
			
			// aapt resource value: 0x7f090010
			public const int content_frame = 2131296272;
			
			// aapt resource value: 0x7f090004
			public const int divCancel = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int divSave = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int divValue = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int divValueText = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public const int drawer_layout = 2131296271;
			
			// aapt resource value: 0x7f09000b
			public const int firstTextView = 2131296267;
			
			// aapt resource value: 0x7f090008
			public const int icInfoTable = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int icTitle = 2131296263;
			
			// aapt resource value: 0x7f09000e
			public const int ifAfterSignInLayout = 2131296270;
			
			// aapt resource value: 0x7f09000a
			public const int ifBeforeSignInLayout = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int ifGeneralLayout = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int ifSignInButton = 2131296268;
			
			// aapt resource value: 0x7f090006
			public const int imageView1 = 2131296262;
			
			// aapt resource value: 0x7f09001a
			public const int largeText = 2131296282;
			
			// aapt resource value: 0x7f090011
			public const int left_drawer = 2131296273;
			
			// aapt resource value: 0x7f090002
			public const int linearLayout1 = 2131296258;
			
			// aapt resource value: 0x7f090050
			public const int llDanger = 2131296336;
			
			// aapt resource value: 0x7f090049
			public const int llInfo = 2131296329;
			
			// aapt resource value: 0x7f09004c
			public const int llSuccess = 2131296332;
			
			// aapt resource value: 0x7f09004e
			public const int llWarning = 2131296334;
			
			// aapt resource value: 0x7f09001b
			public const int lvMerchantInfo = 2131296283;
			
			// aapt resource value: 0x7f090019
			public const int mfContent = 2131296281;
			
			// aapt resource value: 0x7f090017
			public const int mfFullContent = 2131296279;
			
			// aapt resource value: 0x7f090015
			public const int mfHorizontalScrollView = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int mfRelativeLayout = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int mfScrollView = 2131296278;
			
			// aapt resource value: 0x7f090013
			public const int mfSelectedPharmacySpinner = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int mfSelectedPharmacyText = 2131296274;
			
			// aapt resource value: 0x7f090021
			public const int pdePharmacyAddressEdit = 2131296289;
			
			// aapt resource value: 0x7f090020
			public const int pdePharmacyAdressText = 2131296288;
			
			// aapt resource value: 0x7f090025
			public const int pdePharmacyCancelButton = 2131296293;
			
			// aapt resource value: 0x7f09001f
			public const int pdePharmacyFullNameEdit = 2131296287;
			
			// aapt resource value: 0x7f09001e
			public const int pdePharmacyFullNameText = 2131296286;
			
			// aapt resource value: 0x7f090024
			public const int pdePharmacySaveButton = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int pdePharmacySubwayEdit = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int pdePharmacySubwayText = 2131296290;
			
			// aapt resource value: 0x7f09002b
			public const int pfAddPharmacy = 2131296299;
			
			// aapt resource value: 0x7f09002a
			public const int pfContent = 2131296298;
			
			// aapt resource value: 0x7f09002c
			public const int pfFilter = 2131296300;
			
			// aapt resource value: 0x7f09002d
			public const int pfMore = 2131296301;
			
			// aapt resource value: 0x7f090029
			public const int pfPharmacyAddButton = 2131296297;
			
			// aapt resource value: 0x7f09002f
			public const int pfPharmacyTable = 2131296303;
			
			// aapt resource value: 0x7f09002e
			public const int pfPharmacyTableHeader = 2131296302;
			
			// aapt resource value: 0x7f090031
			public const int pfPharmacyTableRow = 2131296305;
			
			// aapt resource value: 0x7f090034
			public const int pfPharmacyTableRowAddress = 2131296308;
			
			// aapt resource value: 0x7f090033
			public const int pfPharmacyTableRowFullName = 2131296307;
			
			// aapt resource value: 0x7f090032
			public const int pfPharmacyTableRowID = 2131296306;
			
			// aapt resource value: 0x7f090028
			public const int pfSearchButton = 2131296296;
			
			// aapt resource value: 0x7f090027
			public const int pfSearchEdit = 2131296295;
			
			// aapt resource value: 0x7f090026
			public const int pfSearchText = 2131296294;
			
			// aapt resource value: 0x7f09004a
			public const int progressBar1 = 2131296330;
			
			// aapt resource value: 0x7f090036
			public const int rdDangerLayout = 2131296310;
			
			// aapt resource value: 0x7f090037
			public const int rdDangerText = 2131296311;
			
			// aapt resource value: 0x7f09003a
			public const int rdPharmacyPicker = 2131296314;
			
			// aapt resource value: 0x7f09003b
			public const int rdPick = 2131296315;
			
			// aapt resource value: 0x7f090035
			public const int rdSearchPhrase = 2131296309;
			
			// aapt resource value: 0x7f090038
			public const int rdSuccessLayout = 2131296312;
			
			// aapt resource value: 0x7f090039
			public const int rdSuccessText = 2131296313;
			
			// aapt resource value: 0x7f090040
			public const int rdanCancel = 2131296320;
			
			// aapt resource value: 0x7f09003d
			public const int rdanDate = 2131296317;
			
			// aapt resource value: 0x7f09003c
			public const int rdanDecrease = 2131296316;
			
			// aapt resource value: 0x7f09003e
			public const int rdanIncrease = 2131296318;
			
			// aapt resource value: 0x7f09003f
			public const int rdanSave = 2131296319;
			
			// aapt resource value: 0x7f090042
			public const int rfAddPharmacy = 2131296322;
			
			// aapt resource value: 0x7f090046
			public const int rfContent = 2131296326;
			
			// aapt resource value: 0x7f090045
			public const int rfDatePicker = 2131296325;
			
			// aapt resource value: 0x7f090043
			public const int rfFilter = 2131296323;
			
			// aapt resource value: 0x7f090041
			public const int rfMain = 2131296321;
			
			// aapt resource value: 0x7f090044
			public const int rfMore = 2131296324;
			
			// aapt resource value: 0x7f09000d
			public const int scrollView1 = 2131296269;
			
			// aapt resource value: 0x7f090056
			public const int sfList = 2131296342;
			
			// aapt resource value: 0x7f090054
			public const int sfSelectedDateSpinner = 2131296340;
			
			// aapt resource value: 0x7f090053
			public const int sfSelectedDateText = 2131296339;
			
			// aapt resource value: 0x7f090055
			public const int sfSyncImage = 2131296341;
			
			// aapt resource value: 0x7f09005b
			public const int sfiDelimiterView = 2131296347;
			
			// aapt resource value: 0x7f090059
			public const int sfiLocationText = 2131296345;
			
			// aapt resource value: 0x7f090057
			public const int sfiRelativeLayout = 2131296343;
			
			// aapt resource value: 0x7f09005a
			public const int sfiStatusImage = 2131296346;
			
			// aapt resource value: 0x7f090058
			public const int sfiTypeInfoText = 2131296344;
			
			// aapt resource value: 0x7f090051
			public const int sidProgressDanger = 2131296337;
			
			// aapt resource value: 0x7f09004b
			public const int sidProgressInfo = 2131296331;
			
			// aapt resource value: 0x7f09004d
			public const int sidProgressSuccess = 2131296333;
			
			// aapt resource value: 0x7f09004f
			public const int sidProgressWarning = 2131296335;
			
			// aapt resource value: 0x7f09005c
			public const int tableLayout1 = 2131296348;
			
			// aapt resource value: 0x7f09005d
			public const int tableRow1 = 2131296349;
			
			// aapt resource value: 0x7f090005
			public const int text = 2131296261;
			
			// aapt resource value: 0x7f090030
			public const int textView1 = 2131296304;
			
			// aapt resource value: 0x7f09005f
			public const int textView14 = 2131296351;
			
			// aapt resource value: 0x7f090060
			public const int textView17 = 2131296352;
			
			// aapt resource value: 0x7f09001c
			public const int textView2 = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int textView3 = 2131296285;
			
			// aapt resource value: 0x7f090048
			public const int txtPassword = 2131296328;
			
			// aapt resource value: 0x7f090047
			public const int txtUsername = 2131296327;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DrugInfoValueDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int InfoCard = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int InfoFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LeftDrawerItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainFragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MerchantInfo = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PharmacyDialogEdit = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PharmacyFragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PharmacyFragmentTableRow = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RoutDialog = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int RoutDialogAddNew = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int RoutDialogSpinnerItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int RoutFragment = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SignInDialog = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SyncFragment = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int SyncFragmentItem = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Testing = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int mfActionBar = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int action_websearch = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int app_not_available = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int drawer_close = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int drawer_open = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f07000d
			public const int Mono_Android_Theme_Splash = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int alert_danger = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int alert_info = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int alert_success = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int alert_warning = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int headerTextForPharmacy = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int headerTextForRout = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int rowTextForPharmacy = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int text_danger = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int text_danger_small = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int text_row = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int text_success = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int text_success_small = 2131165194;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
