#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DroidTest.Resource", IsApplication=true)]

namespace DroidTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_up = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int planets_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bottomline = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonSignUpStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int drawer_shadow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_text_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_add_circle_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_add_circle_black_48dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_add_circle_outline_black_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_drawer = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_filter_list_black_48dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_launcher = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_more_vert_black_48dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int monoandroidsplash = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int progress_info = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int topline = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080046
			public const int btnDialogEmail = 2131230790;
			
			// aapt resource value: 0x7f08000f
			public const int button1 = 2131230735;
			
			// aapt resource value: 0x7f080049
			public const int checkBox1 = 2131230793;
			
			// aapt resource value: 0x7f08000b
			public const int content_frame = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int drawer_layout = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int firstTextView = 2131230726;
			
			// aapt resource value: 0x7f08000d
			public const int horizontalScrollView1 = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int icInfoTable = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int icTitle = 2131230722;
			
			// aapt resource value: 0x7f080009
			public const int ifAfterSignInLayout = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int ifBeforeSignInLayout = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int ifGeneralLayout = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int ifSignInButton = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int imageView1 = 2131230721;
			
			// aapt resource value: 0x7f080010
			public const int largeText = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int left_drawer = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int linearLayout1 = 2131230734;
			
			// aapt resource value: 0x7f080044
			public const int llDanger = 2131230788;
			
			// aapt resource value: 0x7f08003d
			public const int llInfo = 2131230781;
			
			// aapt resource value: 0x7f080040
			public const int llSuccess = 2131230784;
			
			// aapt resource value: 0x7f080042
			public const int llWarning = 2131230786;
			
			// aapt resource value: 0x7f080011
			public const int lvMerchantInfo = 2131230737;
			
			// aapt resource value: 0x7f080017
			public const int pdePharmacyAddressEdit = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int pdePharmacyAdressText = 2131230742;
			
			// aapt resource value: 0x7f08001b
			public const int pdePharmacyCancelButton = 2131230747;
			
			// aapt resource value: 0x7f080015
			public const int pdePharmacyFullNameEdit = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int pdePharmacyFullNameText = 2131230740;
			
			// aapt resource value: 0x7f08001a
			public const int pdePharmacySaveButton = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int pdePharmacySubwayEdit = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int pdePharmacySubwayText = 2131230744;
			
			// aapt resource value: 0x7f080021
			public const int pfAddPharmacy = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int pfContent = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int pfFilter = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int pfMore = 2131230755;
			
			// aapt resource value: 0x7f08001f
			public const int pfPharmacyAddButton = 2131230751;
			
			// aapt resource value: 0x7f080025
			public const int pfPharmacyTable = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int pfPharmacyTableHeader = 2131230756;
			
			// aapt resource value: 0x7f080027
			public const int pfPharmacyTableRow = 2131230759;
			
			// aapt resource value: 0x7f08002a
			public const int pfPharmacyTableRowAddress = 2131230762;
			
			// aapt resource value: 0x7f080029
			public const int pfPharmacyTableRowFullName = 2131230761;
			
			// aapt resource value: 0x7f080028
			public const int pfPharmacyTableRowID = 2131230760;
			
			// aapt resource value: 0x7f08001e
			public const int pfSearchButton = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int pfSearchEdit = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int pfSearchText = 2131230748;
			
			// aapt resource value: 0x7f08003e
			public const int progressBar1 = 2131230782;
			
			// aapt resource value: 0x7f08002c
			public const int rdDangerLayout = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int rdDangerText = 2131230765;
			
			// aapt resource value: 0x7f080030
			public const int rdPharmacyPicker = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int rdPick = 2131230769;
			
			// aapt resource value: 0x7f08002b
			public const int rdSearchPhrase = 2131230763;
			
			// aapt resource value: 0x7f08002e
			public const int rdSuccessLayout = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int rdSuccessText = 2131230767;
			
			// aapt resource value: 0x7f080033
			public const int rdanDate = 2131230771;
			
			// aapt resource value: 0x7f080032
			public const int rdanDecrease = 2131230770;
			
			// aapt resource value: 0x7f080034
			public const int rdanIncrease = 2131230772;
			
			// aapt resource value: 0x7f080036
			public const int rfAddPharmacy = 2131230774;
			
			// aapt resource value: 0x7f08003a
			public const int rfContent = 2131230778;
			
			// aapt resource value: 0x7f080039
			public const int rfDatePicker = 2131230777;
			
			// aapt resource value: 0x7f080037
			public const int rfFilter = 2131230775;
			
			// aapt resource value: 0x7f080035
			public const int rfMain = 2131230773;
			
			// aapt resource value: 0x7f080038
			public const int rfMore = 2131230776;
			
			// aapt resource value: 0x7f080008
			public const int scrollView1 = 2131230728;
			
			// aapt resource value: 0x7f080045
			public const int sidProgressDanger = 2131230789;
			
			// aapt resource value: 0x7f08003f
			public const int sidProgressInfo = 2131230783;
			
			// aapt resource value: 0x7f080041
			public const int sidProgressSuccess = 2131230785;
			
			// aapt resource value: 0x7f080043
			public const int sidProgressWarning = 2131230787;
			
			// aapt resource value: 0x7f080047
			public const int tableLayout1 = 2131230791;
			
			// aapt resource value: 0x7f080048
			public const int tableRow1 = 2131230792;
			
			// aapt resource value: 0x7f080000
			public const int text = 2131230720;
			
			// aapt resource value: 0x7f080026
			public const int textView1 = 2131230758;
			
			// aapt resource value: 0x7f08004a
			public const int textView14 = 2131230794;
			
			// aapt resource value: 0x7f08004b
			public const int textView17 = 2131230795;
			
			// aapt resource value: 0x7f080012
			public const int textView2 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int textView3 = 2131230739;
			
			// aapt resource value: 0x7f08003c
			public const int txtPassword = 2131230780;
			
			// aapt resource value: 0x7f08003b
			public const int txtUsername = 2131230779;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FragmentLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int InfoCard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int InfoFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LeftDrawerItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MerchantInfo = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PharmacyDialogEdit = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PharmacyFragment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PharmacyFragmentTableRow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int RoutDialog = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RoutDialogAddNew = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int RoutDialogSpinnerItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int RoutFragment = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SignInDialog = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Testing = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int action_websearch = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int app_not_available = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int drawer_close = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int drawer_open = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070009
			public const int Mono_Android_Theme_Splash = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int alert_danger = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int alert_info = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int alert_success = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int alert_warning = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int headerTextForPharmacy = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int headerTextForRout = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int rowTextForPharmacy = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int text_row = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
